[tool.poetry]
name = "pointnet2-pytorch"
version = "0.1.0"
description = ""
authors = ["yanx27"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
torch = "<2.0.1"
numpy = "<1.24"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
